### ISSUE TITLE
In which version of Python should we do the project?

### ISSUE THREAD

**Issue by MTHSBGN** [glouppe/info8006-introduction-to-ai#2]
If I recall correctly, you said that we should do it in python 3.5/3.6 but the code of the first project seems to be done using python 2.7 (e.g. print statements).

**Comment by glouppe** [comment]
Thanks Mathias. Indeed, the code should be written in Python 3.

@epochstamp Can you update the templates to make them Python 3 compliant? Thanks!

**Comment by epochstamp** [comment]
Thanks Mathias,

The code has just been updated to run with Python 3. Sorry for the inconvenience.

Samy.
