### ISSUE TITLE
Pacman Project

### ISSUE THREAD

**Issue by PaLeroy** [glouppe/info8006-introduction-to-ai#25]
Pacman module is not working on young python versions on OSx. This comes from a problem between tkinter and OSx update.
For me, downgrading to python6.6 is working.
We should add `conda create -n pacman3_6_6 python=3.6.6` for Mac Os users.

**Comment by PaLeroy** [comment]
> "You may want to have a look at the file util.py in order find a suitable data structure for the exploration of the game tree."

Maybe specify that this file is in the pacman_module directory.

**Comment by PaLeroy** [comment]
Add in the Project 1 statement that the function `s.generatePacmanSuccessors()` MUST be used.

**Comment by glouppe** [comment]
@PaLeroy I upgraded your credentials. You can now make changes yourself :) Thanks for the fixes!

**Comment by PaLeroy** [comment]
Link the submit plateform in the statement.
