### ISSUE TITLE
About the time budget

### ISSUE THREAD

**Issue by CorentinJ** [glouppe/info8006-introduction-to-ai#3]
Is it 1 minute per turn or for the entire game? And shouldn't it be proportional to the size of the grid? If the latter is implemented, the move() function of the Agent class could also receive the information of the time remaining. If the time budget remains fixed however, could it be made shorter for games to be more interesting to watch?

**Comment by glouppe** [comment]
CC: @epochstamp

**Comment by epochstamp** [comment]
Hi Corentin,

Time budget for each move is ~1 minute, and this is true for any grid. We have decided to bound the maximum size of the grid to 1Kx1K.

I'm not sure to see why you would need to have the time information in the move function ? One way to get track of the time budget would be to get it at the beginning of your function and then to check it at each iteration ? Please be more specific about it.

You can decrease the variable TIMEOUT in the game.py file to make it shorter, but at the evaluation it will be at 1 minute anyway.

If you have others questions, do not hesitate,

Samy.

**Comment by CorentinJ** [comment]
Well, I am working with the (possibly false) assumption that there is no agent that can play optimally for an arbitrary large grid size, and therefore that what is to be implemented can be only a heuristic that will yield results proportional to the time allotted (but again, I may very well be wrong). 

If that is the case, one would probably like to let the heuristic run for as long as possible. Looking at the implementation, it can be tricky to return the current best move evaluated just before the time runs out. Now, since you confirmed that the time budget will always be of 1 minute and not something much shorter (e.g. 1 millisecond), I do not think there will be any problem of the kind as one could always return early at the relatively low cost of 1 second (for example).

**Comment by epochstamp** [comment]
"Well, I am working with the (possibly false) assumption that there is no agent that can play optimally for an arbitrary large grid size"

Technically, such an agent exists. But indeed, the complexity of the computation of such an agent increases exponentially with the size of the grid (and thus, the game tree). I'll let you refer to the course for alternatives. 

Anyway, as we are aware of time instabilities, any game between two given opponents will be run several times to stabilize the score.

N.B : I think I'll also add a time limit for the game itself (something between 1 and 3 hours). I'll update the subject as soon as I figured out such a limit.
