### ISSUE TITLE
Function step() of tictactoe.py does not always properly update player turn

### ISSUE THREAD

**Issue by CorentinJ** [glouppe/info8006-introduction-to-ai#5]
There is one execution path where self.currentX is not updated and it can occur even on valid moves. Below is a case where the random agent (p2) play all moves at once after human (p1) has played. The reverse can happen as well.

![image](https://user-images.githubusercontent.com/12038136/32395940-90077768-c0e3-11e7-9c68-8dee5990ccfd.png)

**Comment by glouppe** [comment]
Thanks for the bug report. CC: @epochstamp

**Comment by epochstamp** [comment]
Hi Corentin,

Thanks for reporting the bug, I'm going to check right now. Did you set k=2 in your grid ?

**Comment by epochstamp** [comment]
If k=2, this may not be a bug. Let me explain : 

When you hit an alignment, you also get the next turn. And after your turn ("X"), if your opponent didn't (randomly) pick the last line, he has to have drawn an alignment. Then he grabbed also the next turn, chose another cell which allowed him to draw another alignment, and so on.

Try to launch several games, you'll notice it does not happen every time.

**Comment by CorentinJ** [comment]
Oh I see, I didn't know that rule was there. I think it's missing from the project statement?

**Comment by epochstamp** [comment]
I just modified the document to include that rule, sorry !
