### ISSUE TITLE
Ill-named random.py file

### ISSUE THREAD

**Issue by flopeters1337** [glouppe/info8006-introduction-to-ai#6]
Naming the random agent's file `random.py` causes compatibility issues. 
For instance, PyCharm's debugger fails at launch with the following error : `ImportError: cannot import name 'Random'`
Changing that file's name resolves the issue.

**Comment by epochstamp** [comment]
Hi Florian,

Thanks for the bug report. I just renamed it to randy.py (and Randy).

Samy
