### ISSUE TITLE
Using the distributions of the ghost agents

### ISSUE THREAD

**Issue by CorentinJ** [glouppe/info8006-introduction-to-ai#8]
We can retrieve the probability distribution of the directions to take for a given agent in a given state using 
`agent.getDistribution(state)`

So far, we've assumed that we're allowed to use this function. However, it is problematic for Randyghost as it returns the distribution _after_ it has picked which agent it will mimic, and using this information amounts to cheating. Nonetheless, we'd like to use the function `getDistribution` for the agent Greedyghost and Leftyghost so that we don't have to just rewrite that code ourselves. Then we would just reimplement the distribution for Randyghost. Is this fine by you?

**edit**: a small correction: it does not actually amount to cheating as the distribution you will retrieve will be a new randomly picked one, so it would actually give false information

**Comment by epochstamp** [comment]
Hi Corentin,

"So far, we've assumed that we're allowed to use this function"
Indeed, I don't see any problem to proceed this way.

"Then we would just reimplement the distribution for Randyghost. Is this fine by you?" As long as it helps you on your own implementation, I don't see any problem for that too (same applies for rpickyghost).

Regards,

Samy Aittahar.
